Atoz.Web/Controllers/ConnectController.cs
using System.Net;
using System.Web.Mvc;
using Atoz.Web.Services;

namespace Atoz.Web.Controllers
{
    public class ConnectController : Controller
    {
        private readonly IConnectService connectService;

        public ConnectController(IConnectService connectService)
        {
            this.connectService = connectService;
        }

        public ActionResult Sponsor(int r, int s)
        {
            this.connectService.SponsorResource(r, s);
            return new HttpStatusCodeResult(HttpStatusCode.Accepted);
        }

        public ActionResult Request(int s, int r)
        {
            this.connectService.RequestResource(s, r);
            return new HttpStatusCodeResult(HttpStatusCode.Accepted);
        }

        public ActionResult Accept(int r, int s)
        {
            this.connectService.Accept(r, s);
            return new HttpStatusCodeResult(HttpStatusCode.Accepted);
        }
    }
}

Atoz.Web/Controllers/ProfileController.cs
using Atoz.Web.Services;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;

namespace Atoz.Web.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IProjectsService service;

        public ProfileController(IProjectsService service)
        {
            this.service = service;
        }
        
        public ActionResult MyProjects()
        {
            string userId = GetCurrentUserId();

            var viewModel = service.GetMyProjects(userId);

            return View("Index",viewModel);
        }

        public ActionResult MyResources()
        {
            string userId = GetCurrentUserId();

            var viewModel = service.GetMyResources(userId);

            return View("OfferResource", viewModel);
        }


        private string GetCurrentUserId()
        {
            var userId = string.Empty;
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);

                if (userIdClaim != null)
                {
                    userId = userIdClaim.Value;
                }
            }

            return userId;
        }
    }
}

Atoz.Web/Controllers/TagsController.cs
using System.Web.Mvc;
using Atoz.Web.Services;

namespace Atoz.Web.Controllers
{
    public class TagsController : Controller
    {
        private readonly ITagsService service;
        private readonly IProjectsService _projectsService;
        private readonly IResourcesService _resourcesService;

        public TagsController(ITagsService service, IProjectsService projectsService, IResourcesService resourcesService)
        {
            this.service = service;
            _projectsService = projectsService;
            _resourcesService = resourcesService;
        }

        [HttpGet]
        public ActionResult Get(string prefix)
        {
            return Json(service.Get(prefix), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            var model = this.service.GetTop(20);
            return this.View("Index", model);
        }

        public ActionResult DetailsProject(string tag)
        {
            var model = this._projectsService.GetProjectsByTag(tag);
            return this.View("DetailsProject", model);
        }

        public ActionResult DetailsResource(string tag)
        {
            var model = this._resourcesService.GetResourcesByTag(tag);
            return this.View("DetailsResource", model);
        }
    }
}

Atoz.Web/Views/Shared/HtmlEditorPartial.cshtml
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

<script type="text/javascript">
    // https://www.tinymce.com/docs/
    tinymce.init({
        selector: '.html-editor',
        encoding: 'xml',
        plugins: [
            "advlist autolink lists link image charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars code fullscreen",
            "insertdatetime media nonbreaking save table contextmenu directionality",
            "emoticons template paste textcolor colorpicker textpattern imagetools"
        ],
        toolbar1: "undo redo | pastetext | styleselect fontselect fontsizeselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent",
        toolbar2: "link image | preview media | forecolor backcolor emoticons",
        setup: function (ed) {
            ed.on('init', function () {
                this.execCommand("fontSize", false, "20px");
            });
        }
    });
</script>

Atoz.Web/Views/Shared/LikeDislikePartial.cshtml
@model Atoz.Web.Models.ViewModels.LikeDislikeViewModel

<style>
    .red {
        color: red;
    }
    .glyphicon {
        font-size: 20px;
    }
    .like {
        font-size: 20px;
    }
    .dislike {
        font-size: 20px;
    }
</style>

<script>
    $(document).ready(function() {
        $('button.like').click(function() {
            var url = $(this).attr('dataUrl');
            $.ajax({
                data: {
                    id: @Model.ProjectId
                },
                type: "POST",
                url: url,
                success: function() {
                    location.reload();
                }
            });

        });
    });
</script>
<button class="btn like @(Model.HasUserAlreadyLiked? "red" : string.Empty)" @(Model.HasUserAlreadyLiked? "disabled" : string.Empty)  dataUrl="@Url.Action("Like", "Projects", new {id = Model.ProjectId})">
    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> @Model.LikeCount
</button>

<script>
    $(document).ready(function() {
        $('button.dislike').click(function() {
            var url = $(this).attr('dataUrl');
            $.ajax({
                data: {
                    id: @Model.ProjectId
                },
                type: "POST",
                url: url,
                success: function() {
                    location.reload();
                }
            });

        });
    });
</script>
<button class="btn dislike @(Model.HasUserAlreadyDisliked? "red" : string.Empty)" @(Model.HasUserAlreadyDisliked ? "disabled" : string.Empty) dataUrl="@Url.Action("Dislike", "Projects", new { id = Model.ProjectId })">
    <span class="glyphicon glyphicon-cloud" aria-hidden="true"></span> @Model.DislikeCount
</button>

Atoz.Web/Views/Shared/TagitPartial.cshtml
<script type="text/javascript">
    // https://github.com/aehlke/tag-it
    $(document).ready(function () {
        $("#tags").tagit({
            singleFieldDelimiter: ';',
            autocomplete: {
                delay: 500,
                minLength: 3,
                placeholderText: 'add Tags here...',
                source: function (request, response) {
                    $.ajax({
                        url: '@Url.Action("Get", "Tags")',
                        dataType: "json",
                        type: "GET",
                        contentType: "application/json; charset=utf-8",
                        data: {
                            prefix: request.term
                        },
                        success: function (data) {
                            response(data);
                        }
                    });
                }
            }
        });
    });
</script>

Atoz.Web/Views/Shared/_DropdownInception.cshtml
@model Atoz.Web.Models.ViewModels.ResourceDetailsViewModel

<div class="navbar navbar-default col-sm-3">
    <div class="collapse navbar-collapse bs-example-js-navbar-collapse">
        <ul class="nav navbar-nav">
            <li class="dropdown"> 
                <a href="#" data-toggle="dropdown"> Wybierz potrzebny zasób <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    @foreach (var project in Model.RequiredRecourses.Projects)
                    {
                        <li class="dropdown-submenu"> 
                            <a href="#" data-toggle="dropdown"> @project.Title</a>
                            <ul class="dropdown-menu">
                                @foreach (var resource in project.RequiredResources)
                                {
                                    <li>
                                        <a href="#" tabindex="-1" class="nocss-requested-resource" data-url="@Url.Action("Request", "Connect", new {r = resource.Id, s = Model.Id})"="@resource.Id">@resource.Description</a>
                                    </li>
                                }
                            </ul>
                        </li>
                    }
                </ul>
            </li>
        </ul>
    </div>
</div>

Atoz.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AtoZ</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="~/Content/dropdowns-enhancement.min.css" rel="stylesheet" />
    <script src="~/Content/dropdowns-enhancement.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <style>
        .label {
            font-size: 15px;
        }
    </style>
</head>
<body>
    <div id="fb-root"></div>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("A...Z", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="@Url.Action("Index", "Projects")" role="button" aria-haspopup="true" aria-expanded="false">
                            Projekty <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Lista", "Index", "Projects")</li>
                            <li>@Html.ActionLink("Nowy", "Create", "Projects")</li>
                            <li>@Html.ActionLink("Szukaj", "Search", "Projects")</li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li>@Html.ActionLink("Moje Projekty", "MyProjects", "Profile")</li>
                            }
                        </ul>
                    </li>

                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="@Url.Action("Index","Resources")" role="button" aria-haspopup="true" aria-expanded="false">
                            Materiały <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Lista", "Index", "Resources")</li>
                            <li>@Html.ActionLink("Nowy", "Create", "Resources")</li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li>@Html.ActionLink("Moje Zasoby", "MyResources", "Profile")</li>
                            }
                        </ul>
                    </li>

                    <li>@Html.ActionLink("Tagi", "Index", "Tags")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AtoZ</p>
        </footer>
    </div>


    @RenderSection("scripts", required: false)
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/black-tie/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/Scripts/tag-it.min.js"></script>
    <link href="~/Content/jquery.tagit.css" rel="stylesheet" />
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.6&appId=1586507994995198";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));

        $(function() {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</body>
</html>